name: "Setup node and install dependencies"
description: "Takes care of the copy-pasta for the cache handling of pnpm"
inputs:
  install:
    description: "Should we run the install command?"
    required: false
    default: true
  node-version:
    description: "The version of node to use"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4.0.0
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
        run_install: false
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4.0.4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
      if: inputs.install == 'true'
      shell: bash
