name: "Setup node and install dependencies"
description: "Takes care of the copy-pasta for the cache handling of pnpm"
inputs:
  install:
    description: "Should we run the install command?"
    required: false
    default: true
  cache-name:
    description: "The name of the cache to use"
    required: true
  node-version:
    description: "The version of node to use"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3.5.1
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@v2.2.4
      name: Install pnpm
      if: inputs.install == 'true'
      id: pnpm-install
      with:
        version: latest
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Cache build helpers
      id: cache-build-data
      uses: pat-s/always-upload-cache@v3.0.11
      if: always()
      env:
        cache-name: cache-build-data
      with:
        path: ./.cache
        key: ${{ runner.os }}-build-data-${{ inputs.cache-name }}

    - uses: pat-s/always-upload-cache@v3.0.11
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ inputs.cache-name }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install --frozen-lockfile
      shell: bash
